import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { PrimaryButton } from "../components/atoms/button/PrimaryButton";
import { Header } from "../components/organisms/leyout/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cat Family 猫好きのための里親コミュニティ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container my-0 lg:mx-auto md:w-screen">
        <Header />
      </div>
    </>
  );
};

export default Home;
