# rubocop -aで実行
AllCops:
  Exclude:
    - bin/*
    - db/schema.rb

# 日本語コメント許可
AsciiComments:
  Enabled: false

# ダブルクォーテーションに統一
StringLiterals:
  EnforcedStyle: double_quotes

# メソッドの長さ
Metrics/MethodLength:
Exclude:
    - "db/migrate/**/*"

# AbcSize
+ Metrics/AbcSize:
+   Exclude:

# 行の長さ
+ Layout/LineLength:
+   Exclude:
      - "config/initializers/**/*"